export const cards = [
  {
    id: 0,
    country: "تركيا",
    persons: " عرض لشخصين",
    price: "سعر البرنامج 6000",
    discount: 6500,
    priceItem: 6000,
    image: "/images/card-turkey.jpg",
  },
  {
    id: 1,
    country: "اذبريجان",
    persons: " عرض لشخصين",
    price: "سعر البرنامج 3250",
    discount: 3700,
    priceItem: 3250,
    image: "/images/card-asbirijan.jpg",
  },
  {
    id: 2,
    country: "مصر",
    persons: " عرض لشخصين",
    price: "سعر البرنامج 5700",
    discount: 6500,
    priceItem: 5700,
    image: "/images/card-egypt.jpg",
  },
  {
    id: 3,
    country: "شاطئ المالديف",
    persons: " عرض لشخصين",
    price: "سعر البرنامج 5700",
    discount: 6500,
    priceItem: 5700,
    image: "/images/card-maldives.jpg",
  },
  {
    id: 4,
    country: "الهند",
    persons: " عرض لشخصين",
    price: "سعر البرنامج 5700",
    discount: 6500,
    priceItem: 5700,
    image: "/images/card-india.jpg",
  },
  {
    id: 5,
    country: "ابو ظبي",
    persons: " عرض لشخصين",
    price: "سعر البرنامج 8600",
    discount: 9000,
    priceItem: 8600,
    image: "/images/card-abudubai.jpg",
  },
  {
    id: 6,
    country: "قطر",
    persons: " عرض لشخصين",
    price: "سعر البرنامج 3600",
    discount: 4000,
    priceItem: 3600,
    image: "/images/card-qatar.jpg",
  },
];
