export const cards = [
  {
    id: 0,
    country: "تركيا",
    persons: " عرض لشخصين",
    price: "سعر البرنامج 6000",
    discount: "بدلا من 6500",
    image: "/images/card-turkey.jpg",
  },
  {
    id: 1,
    country: "اذبريجان",
    persons: " عرض لشخصين",
    price: "سعر البرنامج 3250",
    discount: "بدلا من 3700",
    image: "/images/card-asbirijan.jpg",
  },
  {
    id: 2,
    country: "مصر",
    persons: " عرض لشخصين",
    price: "سعر البرنامج 5700",
    discount: "بدلا من 6500",
    image: "/images/card-egypt.jpg",
  },
  {
    id: 3,
    country: "شاطئ المالديف",
    persons: " عرض لشخصين",
    price: "سعر البرنامج 5700",
    discount: "بدلا من 6500",
    image: "/images/card-maldives.jpg",
  },
  {
    id: 4,
    country: "الهند",
    persons: " عرض لشخصين",
    price: "سعر البرنامج 5700",
    discount: "بدلا من 6500",
    image: "/images/card-india.jpg",
  },
  {
    id: 5,
    country: "ابو ظبي",
    persons: " عرض لشخصين",
    price: "سعر البرنامج 8600",
    discount: "بدلا من 9000",
    image: "/images/card-abudubai.jpg",
  },
  {
    id: 6,
    country: "قطر",
    persons: " عرض لشخصين",
    price: "سعر البرنامج 3600",
    discount: "بدلا من 4000",
    image: "/images/card-qatar.jpg",
  },
];
